### ISSUE TITLE
Use output parameters as part of CMD_Render

### ISSUE THREAD

**Issue by nuest** [o2r-project/containerit#180]
We should re-use the existing output parameters for the `html_document` output type, see https://github.com/o2r-project/containerit/blob/51d7b2679623492dc4e09a4baeb31affdf96b686/R/Class-Cmd.R#L163

If an R Markdown document configures the output as follows, the `toc` configuration is lost in the documented rendered by the container:

```yaml
output:
  html_document:
    df_print: paged
    toc: yes
```
